version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - "${PWD}/rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins"